set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(MSVC)
	set(COMPILER_FOLDER "MSVC")
elseif(MINGW)
	set(COMPILER_FOLDER "Mingw64")
endif()

set(OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/${COMPILER_FOLDER}-${CMAKE_BUILD_TYPE}")

set(CMAKE_INSTALL_PREFIX "${OUTPUT_DIRECTORY}/package/${PROJECT_NAME}-${COMPILER_FOLDER}")
set(CPACK_OUTPUT_FILE_PREFIX "${OUTPUT_DIRECTORY}/package")

set(CPACK_PACKAGE_NAME "${PROJECT_NAME}-${COMPILER_FOLDER}")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${COMPILER_FOLDER}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}-${COMPILER_FOLDER}")