

SELECT [FORMALNAME], [AOLEVEL], [PLAINCODE], COUNT(*) AS CNT
FROM [FIAS_TABLE]
GROUP BY [FORMALNAME], [AOLEVEL], [PLAINCODE]
HAVING COUNT(*) > 1


begin tran

DELETE FROM [FIAS_TABLE]
WHERE ID NOT IN
(
    SELECT MAX(ID) AS MaxRecordID
    FROM [FIAS_TABLE]
	GROUP BY [FORMALNAME], [AOLEVEL], [PLAINCODE]
)

rollback tran
